for %%f in (*copy.*) do pause
for %%f in (*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_kaiser.dpf" "%%f"
for %%f in (*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_kaiser.dpf" "%%f"
for %%f in (*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_kaiser.dpf" "%%f"
for %%f in (*_sub_*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_sub_*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_sub_*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_sub.*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_sub.*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_sub.*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod1*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod1*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod1*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod2*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod2*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod2*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod0*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod0*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_mod0*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_bmap*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_bmap*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_bmap*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_chuou*.png) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_chuou*.psd) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
for %%f in (*_chuou*.tga) do "C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools\nvtt_export.exe" -p "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs_nomips.dpf" "%%f"
set curr_directory=%cd%
cd /d "J:\Mega\Games\MG Master Collection\Self made mods\Tooling\CTXR File Conversion\mgs3-param" 
timeout 1 /nobreak
for %%f in ("%curr_directory%\*.dds") do "CtxrTool.exe" "%%f"
timeout 1 /nobreak
for %%f in (*.ctxr) do MOVE "%%f" "%curr_directory%\%%f"
for %%f in ("%curr_directory%\*.dds") do del "%%f"